[build]
  command = "npm install && npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "false" 
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-optional"

# Redirect rules for common URL patterns
[[redirects]]
  from = "/reddit%20Automation"
  to = "/reddit-automation"
  status = 301

[[redirects]]
  from = "/reddit Automation"
  to = "/reddit-automation"
  status = 301

[[redirects]]
  from = "/appreddit-automation"
  to = "/reddit-automation"
  status = 301

[[redirects]]
  from = "/app/reddit-automation"
  to = "/reddit-automation"
  status = 301

# Handle Next.js App Router
[[redirects]]
  from = "/reddit-automation"
  to = "/reddit-automation"
  status = 200

# Handle client-side routing for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200