[build]
  command = "npm install && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true" 
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-optional"

# Redirect rules for common URL patterns
[[redirects]]
  from = "/reddit%20Automation"
  to = "/reddit-automation"
  status = 301

[[redirects]]
  from = "/reddit Automation"
  to = "/reddit-automation"
  status = 301

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200