[build]
   command = "pnpm install && pnpm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true" 
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-optional"